"""Adapters module: Pluggable Embedding models and LLM providers."""

from trace_lite.adapters.embeddings import EmbeddingAdapter, SentenceTransformerEmbedder, MockEmbedder
from trace_lite.adapters.llm import (
    LLMAdapter,
    LiteLLMAdapter,
    MockLLMAdapter,
    OllamaAvailabilityError,
    OllamaModelNotFoundError,
    OllamaServiceUnavailableError,
    LLMPreflightError,
    UnsupportedModelError,
    RejectedCredentialError,
    EndpointUnavailableError,
    TemporaryProviderError,
    EmptyResponseError,
    ProviderResponseError,
    AuthenticationRejectedError,
    CredentialRejectedError,
    ProviderUnavailableError,
    ProviderEndpointUnavailableError,
    RateLimitedProviderError,
    RateLimitedOrTemporaryError,
    EmptyProviderResponseError,
    UnsafeCompletionError,
    NormalizedCompletionEnvelope,
    CompletionEnvelope,
    NormalizedCompletion,
    redact_diagnostic,
)

__all__ = [
    "EmbeddingAdapter",
    "SentenceTransformerEmbedder",
    "MockEmbedder",
    "LLMAdapter",
    "LiteLLMAdapter",
    "MockLLMAdapter",
    "OllamaAvailabilityError",
    "OllamaModelNotFoundError",
    "OllamaServiceUnavailableError",
    "LLMPreflightError",
    "UnsupportedModelError",
    "RejectedCredentialError",
    "EndpointUnavailableError",
    "TemporaryProviderError",
    "EmptyResponseError",
    "ProviderResponseError",
    "AuthenticationRejectedError",
    "CredentialRejectedError",
    "ProviderUnavailableError",
    "ProviderEndpointUnavailableError",
    "RateLimitedProviderError",
    "RateLimitedOrTemporaryError",
    "EmptyProviderResponseError",
    "UnsafeCompletionError",
    "NormalizedCompletionEnvelope",
    "CompletionEnvelope",
    "NormalizedCompletion",
    "redact_diagnostic",
]
