/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  TRACE_LITE_VIEW_TYPE: () => TRACE_LITE_VIEW_TYPE,
  TraceLiteSettingTab: () => TraceLiteSettingTab,
  TraceLiteSidebarView: () => TraceLiteSidebarView,
  default: () => TraceLitePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var TRACE_LITE_VIEW_TYPE = "trace-lite-view";
var DEFAULT_SETTINGS = {
  apiUrl: "http://127.0.0.1:8420",
  autoSyncOnModify: true,
  autoSyncOnCreate: true,
  defaultMode: "hybrid",
  topK: 5
};
var TraceLiteSidebarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.isSearching = false;
    this.plugin = plugin;
  }
  getViewType() {
    return TRACE_LITE_VIEW_TYPE;
  }
  getDisplayText() {
    return "trace-lite RAG Assistant";
  }
  getIcon() {
    return "brain";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("trace-lite-sidebar");
    const headerEl = container.createDiv({ cls: "trace-lite-header" });
    const titleEl = headerEl.createDiv({ cls: "trace-lite-header-title" });
    const iconEl = titleEl.createSpan({ cls: "trace-lite-icon" });
    (0, import_obsidian.setIcon)(iconEl, "brain");
    titleEl.createSpan({ text: "trace-lite Assistant" });
    const statusBadgeEl = headerEl.createDiv({ cls: "trace-lite-status-badge" });
    this.statusDotEl = statusBadgeEl.createDiv({ cls: "trace-lite-status-dot" });
    this.statusTextEl = statusBadgeEl.createSpan({ text: "Checking..." });
    const actionsBarEl = container.createDiv({ cls: "trace-lite-actions-bar" });
    const syncBtn = actionsBarEl.createEl("button", {
      cls: "trace-lite-btn trace-lite-btn-secondary",
      text: "Sync Vault"
    });
    const syncIcon = syncBtn.createSpan({ cls: "trace-lite-btn-icon" });
    (0, import_obsidian.setIcon)(syncIcon, "refresh-cw");
    syncBtn.prepend(syncIcon);
    syncBtn.addEventListener("click", async () => {
      await this.plugin.syncEntireVault();
    });
    const statusRefreshBtn = actionsBarEl.createEl("button", {
      cls: "trace-lite-btn trace-lite-btn-secondary",
      text: "Status"
    });
    statusRefreshBtn.addEventListener("click", async () => {
      await this.checkStatus();
    });
    const searchContainerEl = container.createDiv({ cls: "trace-lite-search-container" });
    const inputWrapperEl = searchContainerEl.createDiv({ cls: "trace-lite-search-input-wrapper" });
    this.searchInputEl = inputWrapperEl.createEl("input", {
      cls: "trace-lite-search-input",
      type: "text",
      placeholder: "Ask or search knowledge base..."
    });
    const searchBtn = inputWrapperEl.createEl("button", {
      cls: "trace-lite-btn",
      text: "Search"
    });
    this.searchInputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        this.runSearch();
      }
    });
    searchBtn.addEventListener("click", () => {
      this.runSearch();
    });
    const controlsRowEl = searchContainerEl.createDiv({ cls: "trace-lite-controls-row" });
    const modeGroupEl = controlsRowEl.createDiv({ cls: "trace-lite-control-group" });
    modeGroupEl.createSpan({ text: "Mode:" });
    this.modeSelectEl = modeGroupEl.createEl("select", { cls: "trace-lite-select" });
    ["hybrid", "tree", "flat"].forEach((m) => {
      const opt = this.modeSelectEl.createEl("option", { value: m, text: m.toUpperCase() });
      if (m === this.plugin.settings.defaultMode) {
        opt.selected = true;
      }
    });
    const topKGroupEl = controlsRowEl.createDiv({ cls: "trace-lite-control-group" });
    topKGroupEl.createSpan({ text: "Top K:" });
    this.topKInputEl = topKGroupEl.createEl("input", {
      cls: "trace-lite-select",
      type: "number",
      value: String(this.plugin.settings.topK)
    });
    this.topKInputEl.style.width = "45px";
    this.topKInputEl.min = "1";
    this.topKInputEl.max = "20";
    container.createDiv({ cls: "trace-lite-results-header", text: "Hierarchical Evidence & Results" });
    this.resultsContainerEl = container.createDiv({ cls: "trace-lite-results-list" });
    this.renderEmptyState("Enter a query above to search the verified source index.");
    await this.checkStatus();
  }
  async checkStatus() {
    try {
      this.statusDotEl.className = "trace-lite-status-dot syncing";
      this.statusTextEl.setText("Connecting...");
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.plugin.settings.apiUrl}/api/status`,
        method: "GET"
      });
      if (response.status === 200) {
        const data = response.json;
        this.statusDotEl.className = "trace-lite-status-dot connected";
        const atoms = data.total_atoms ?? 0;
        const trees = data.total_trees ?? 0;
        const trust = data.index_trusted ? "verified" : "untrusted";
        const pending = data.needs_organization ? ", pending organization" : "";
        this.statusTextEl.setText(`Connected (${atoms} atoms, ${trees} trees; ${trust}${pending})`);
        return true;
      } else {
        throw new Error(`HTTP ${response.status}`);
      }
    } catch (err) {
      this.statusDotEl.className = "trace-lite-status-dot disconnected";
      this.statusTextEl.setText("Offline");
      return false;
    }
  }
  async runSearch() {
    const queryText = this.searchInputEl.value.trim();
    if (!queryText) {
      new import_obsidian.Notice("Please enter a search query.");
      return;
    }
    if (this.isSearching)
      return;
    this.isSearching = true;
    this.resultsContainerEl.empty();
    const loadingState = this.resultsContainerEl.createDiv({ cls: "trace-lite-empty-state" });
    const spinner = loadingState.createDiv({ cls: "trace-lite-spinner" });
    loadingState.createDiv({ text: "Searching the verified RAPTOR/LATTICE index..." });
    const mode = this.modeSelectEl.value;
    const topK = parseInt(this.topKInputEl.value) || 5;
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.plugin.settings.apiUrl}/api/query`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query_text: queryText,
          top_k: topK,
          mode
        })
      });
      if (response.status === 200) {
        const data = response.json;
        this.renderResults(data);
      } else {
        new import_obsidian.Notice(`trace-lite query error: HTTP ${response.status}`);
        this.renderEmptyState(`Error querying server (HTTP ${response.status})`);
      }
    } catch (err) {
      console.error("trace-lite search failed:", err);
      new import_obsidian.Notice(`Failed to connect to trace-lite server at ${this.plugin.settings.apiUrl}`);
      this.renderEmptyState("Failed to connect to trace-lite daemon server.");
      this.checkStatus();
    } finally {
      this.isSearching = false;
    }
  }
  renderResults(data) {
    this.resultsContainerEl.empty();
    if (!data.items || data.items.length === 0) {
      this.renderEmptyState(`No matching evidence found for "${data.query_text}".`);
      return;
    }
    data.items.forEach((item, index) => {
      const card = this.resultsContainerEl.createDiv({ cls: "trace-lite-evidence-card" });
      const topRow = card.createDiv({ cls: "trace-lite-card-top" });
      const docInfo = topRow.createDiv({ cls: "trace-lite-doc-info" });
      const fileIcon = docInfo.createSpan();
      (0, import_obsidian.setIcon)(fileIcon, "file-text");
      const docName = item.source_artifact?.document_name || "Untitled Document";
      docInfo.createSpan({ cls: "trace-lite-doc-name", text: docName });
      const scorePct = Math.round(item.score * 100);
      let scoreClass = "low-score";
      if (item.score >= 0.7)
        scoreClass = "high-score";
      else if (item.score >= 0.4)
        scoreClass = "medium-score";
      const scoreBadge = topRow.createDiv({
        cls: `trace-lite-score-badge ${scoreClass}`,
        text: `${scorePct}% match`
      });
      if (item.traversal_path && item.traversal_path.length > 0) {
        const pathEl = card.createDiv({ cls: "trace-lite-path" });
        pathEl.createSpan({ text: "Hierarchy Path:" });
        item.traversal_path.forEach((step, idx) => {
          if (idx > 0) {
            pathEl.createSpan({ cls: "trace-lite-path-separator", text: "\u2794" });
          }
          pathEl.createSpan({ cls: "trace-lite-path-node", text: step });
        });
      }
      card.createDiv({
        cls: "trace-lite-snippet",
        text: item.atom.content
      });
      const footerEl = card.createDiv({ cls: "trace-lite-card-footer" });
      const linkIcon = footerEl.createSpan();
      (0, import_obsidian.setIcon)(linkIcon, "external-link");
      footerEl.createSpan({ text: "Open in Vault" });
      card.addEventListener("click", () => {
        this.openNoteInVault(docName);
      });
    });
  }
  renderEmptyState(message) {
    this.resultsContainerEl.empty();
    const emptyEl = this.resultsContainerEl.createDiv({ cls: "trace-lite-empty-state" });
    const iconSpan = emptyEl.createDiv({ cls: "trace-lite-empty-icon" });
    (0, import_obsidian.setIcon)(iconSpan, "search");
    emptyEl.createDiv({ text: message });
  }
  async openNoteInVault(docName) {
    let file = this.app.vault.getAbstractFileByPath(docName);
    if (!file && !docName.endsWith(".md")) {
      file = this.app.vault.getAbstractFileByPath(`${docName}.md`);
    }
    if (!file || !(file instanceof import_obsidian.TFile)) {
      const firstDest = this.app.metadataCache.getFirstLinkpathDest(docName, "");
      if (firstDest) {
        file = firstDest;
      }
    }
    if (!file || !(file instanceof import_obsidian.TFile)) {
      const allFiles = this.app.vault.getMarkdownFiles();
      const matched = allFiles.find((f) => f.path.includes(docName) || f.name.includes(docName));
      if (matched) {
        file = matched;
      }
    }
    if (file && file instanceof import_obsidian.TFile) {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
      new import_obsidian.Notice(`Opened note: ${file.basename}`);
    } else {
      this.app.workspace.openLinkText(docName, "", true);
    }
  }
};
var TraceLiteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "trace-lite AI & RAG Assistant Settings" });
    new import_obsidian.Setting(containerEl).setName("trace-lite API Base URL").setDesc("Hostname and port for local trace-lite Python daemon (default http://127.0.0.1:8420).").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:8420").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
        this.plugin.settings.apiUrl = value.trim().replace(/\/+$/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-sync on Note Modification").setDesc("Automatically re-ingest notes into trace-lite when modified in Obsidian.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnModify).onChange(async (value) => {
        this.plugin.settings.autoSyncOnModify = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-sync on Note Creation").setDesc("Automatically ingest new markdown notes into trace-lite upon creation.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnCreate).onChange(async (value) => {
        this.plugin.settings.autoSyncOnCreate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Search Mode").setDesc("Default search algorithm mode for RAG queries (hybrid uses LATTICE + tree summaries).").addDropdown(
      (dropdown) => dropdown.addOption("hybrid", "Hybrid (Vector + RAPTOR Trees)").addOption("tree", "Tree (RAPTOR Summary Forest)").addOption("flat", "Flat (Vector Similarity)").setValue(this.plugin.settings.defaultMode).onChange(async (value) => {
        this.plugin.settings.defaultMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Top K Results").setDesc("Number of evidence cards to retrieve per query (1 to 20).").addSlider(
      (slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.topK).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.topK = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Test Daemon Connection").setDesc("Verify connection status with your trace-lite REST API server.").addButton(
      (button) => button.setButtonText("Check Server").setCta().onClick(async () => {
        try {
          const res = await (0, import_obsidian.requestUrl)({
            url: `${this.plugin.settings.apiUrl}/api/status`,
            method: "GET"
          });
          if (res.status === 200) {
            const info = res.json;
            new import_obsidian.Notice(`\u2713 Successfully connected to trace-lite! (${info.total_atoms ?? 0} atoms indexed)`);
          } else {
            new import_obsidian.Notice(`\u274C Failed to connect: Server returned status code ${res.status}`);
          }
        } catch (e) {
          new import_obsidian.Notice(`\u274C Connection failed. Check if trace-lite daemon is running at ${this.plugin.settings.apiUrl}`);
        }
      })
    );
  }
};
var TraceLitePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      TRACE_LITE_VIEW_TYPE,
      (leaf) => new TraceLiteSidebarView(leaf, this)
    );
    this.addCommand({
      id: "open-trace-lite-assistant",
      name: "trace-lite: Open RAG Assistant",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "sync-current-vault",
      name: "trace-lite: Sync Current Vault",
      callback: async () => {
        await this.syncEntireVault();
      }
    });
    this.addSettingTab(new TraceLiteSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (this.settings.autoSyncOnModify && file instanceof import_obsidian.TFile && file.extension === "md") {
          await this.syncNoteToTraceLite(file, "modified");
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (this.settings.autoSyncOnCreate && file instanceof import_obsidian.TFile && file.extension === "md") {
          await this.syncNoteToTraceLite(file, "created");
        }
      })
    );
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(TRACE_LITE_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: TRACE_LITE_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async syncNoteToTraceLite(file, eventType) {
    try {
      const content = await this.app.vault.read(file);
      const res = await (0, import_obsidian.requestUrl)({
        url: `${this.settings.apiUrl}/api/ingest`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: content,
          document_name: file.path
        })
      });
      if (res.status === 200) {
        console.log(`[trace-lite] Auto-synced ${file.path} (${eventType})`);
      }
    } catch (err) {
      console.warn(`[trace-lite] Auto-sync failed for ${file.path}:`, err);
    }
  }
  async syncEntireVault() {
    const mdFiles = this.app.vault.getMarkdownFiles();
    if (mdFiles.length === 0) {
      new import_obsidian.Notice("No markdown files found in vault to sync.");
      return;
    }
    new import_obsidian.Notice(`Starting trace-lite sync for ${mdFiles.length} note(s)...`);
    let synced = 0;
    let failed = 0;
    for (const file of mdFiles) {
      try {
        const content = await this.app.vault.read(file);
        const res = await (0, import_obsidian.requestUrl)({
          url: `${this.settings.apiUrl}/api/ingest`,
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            text: content,
            document_name: file.path
          })
        });
        if (res.status === 200) {
          synced++;
        } else {
          failed++;
        }
      } catch (err) {
        failed++;
      }
    }
    if (failed === 0) {
      new import_obsidian.Notice(`\u2713 trace-lite: Successfully synced all ${synced} vault note(s)!`);
    } else {
      new import_obsidian.Notice(`trace-lite sync finished: ${synced} succeeded, ${failed} failed.`);
    }
    const leaves = this.app.workspace.getLeavesOfType(TRACE_LITE_VIEW_TYPE);
    for (const leaf of leaves) {
      if (leaf.view instanceof TraceLiteSidebarView) {
        await leaf.view.checkStatus();
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
